apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-repo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/git-repo"   # Path to your local Git repo in Minikube
  storageClassName: manual
